export const dummyAuditLogs = [
  {
    id: "AUD-20260802-0001",
    createdAt: "2026-08-02T08:15:22Z",
    user: "Bapak Agus",
    role: "Admin OPD",
    opd: "Dinas Kesehatan",
    module: "Pengaduan",
    action: "UPDATE",
    objectType: "Pengaduan",
    objectId: "CMP-2026-0089",
    description: "Mengubah status pengaduan menjadi Diproses",
    status: "SUCCESS",
    ipAddress: "192.168.1.45",
    browser: "Chrome 126.0",
    operatingSystem: "Windows 11",
    device: "Desktop",
    sessionId: "sess_89f3a2bc1",
    oldValue: { status: "Diterima" },
    newValue: { status: "Diproses" }
  },
  {
    id: "AUD-20260802-0002",
    createdAt: "2026-08-02T09:00:10Z",
    user: "Sistem Eksekutif",
    role: "System",
    opd: "Semua OPD",
    module: "Dashboard",
    action: "READ",
    objectType: "Report",
    objectId: "RPT-MONTHLY-08",
    description: "Sistem men-generate laporan bulanan otomatis",
    status: "SUCCESS",
    ipAddress: "127.0.0.1",
    browser: "System Agent",
    operatingSystem: "Linux Ubuntu 22.04",
    device: "Server",
    sessionId: "system_cron_job",
    oldValue: null,
    newValue: null
  },
  {
    id: "AUD-20260802-0003",
    createdAt: "2026-08-02T10:30:05Z",
    user: "Ibu Ratna",
    role: "Admin OPD",
    opd: "Dinas PUPR",
    module: "Autentikasi",
    action: "LOGIN",
    objectType: "Session",
    objectId: "USR-0045",
    description: "Pengguna berhasil login ke dalam sistem",
    status: "SUCCESS",
    ipAddress: "10.0.5.12",
    browser: "Firefox 128.0",
    operatingSystem: "Windows 10",
    device: "Desktop",
    sessionId: "sess_44d1e9bb",
    oldValue: null,
    newValue: null
  },
  {
    id: "AUD-20260802-0004",
    createdAt: "2026-08-02T11:15:40Z",
    user: "Admin Sistem",
    role: "Admin Kabupaten",
    opd: "Sekretariat Daerah",
    module: "Pengguna",
    action: "CREATE",
    objectType: "User",
    objectId: "USR-0089",
    description: "Membuat akun baru untuk staf Bappeda",
    status: "SUCCESS",
    ipAddress: "10.0.1.200",
    browser: "Safari 17.4",
    operatingSystem: "macOS Sonoma",
    device: "Desktop",
    sessionId: "sess_aa1129bb",
    oldValue: null,
    newValue: { nama: "Budi Staf", role: "Staf OPD", opd: "Bappeda" }
  },
  {
    id: "AUD-20260802-0005",
    createdAt: "2026-08-02T14:20:00Z",
    user: "Unknown",
    role: "Guest",
    opd: "-",
    module: "Autentikasi",
    action: "LOGIN",
    objectType: "Session",
    objectId: "-",
    description: "Percobaan login gagal (Password salah)",
    status: "FAILED",
    ipAddress: "203.11.22.45",
    browser: "Edge 125.0",
    operatingSystem: "Windows 11",
    device: "Desktop",
    sessionId: "-",
    oldValue: null,
    newValue: null
  },
  {
    id: "AUD-20260801-0020",
    createdAt: "2026-08-01T15:45:12Z",
    user: "Bapak Agus",
    role: "Admin OPD",
    opd: "Dinas Kesehatan",
    module: "Survei",
    action: "DELETE",
    objectType: "Survei",
    objectId: "SRV-2026-001",
    description: "Menghapus draf survei IKM",
    status: "SUCCESS",
    ipAddress: "192.168.1.45",
    browser: "Chrome 126.0",
    operatingSystem: "Windows 11",
    device: "Desktop",
    sessionId: "sess_89f3a2bc1",
    oldValue: { id: "SRV-2026-001", judul: "IKM Semester 1" },
    newValue: null
  }
];
