export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN_KABUPATEN: 'ADMIN_KABUPATEN',
  ADMIN_OPD: 'ADMIN_OPD',
  RESPONDENT: 'RESPONDENT',
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  PENDING: 'PENDING',
};
