export const DUMMY_OPD = [
  {
    id: 1,
    code: 'OPD-DINKES',
    name: 'Dinas Kesehatan Kabupaten Madiun',
    address: 'Jl. Raya Solo-Madiun No. 12',
    serviceType: 'Kesehatan & Jaminan Sosial',
    activeSurveys: 2,
    openComplaints: 5,
    status: 'ACTIVE',
  },
  {
    id: 2,
    code: 'OPD-RSUD',
    name: 'RSUD Dolopo',
    address: 'Unit Pelaksana Teknis Kesehatan',
    serviceType: 'Layanan Kesehatan Umum',
    activeSurveys: 1,
    openComplaints: 12,
    status: 'ACTIVE',
  },
  {
    id: 3,
    code: 'OPD-DIKNAS',
    name: 'Dinas Pendidikan',
    address: 'Pusat Administrasi Pendidikan Daerah',
    serviceType: 'Pendidikan & Kebudayaan',
    activeSurveys: 4,
    openComplaints: 8,
    status: 'ACTIVE',
  },
  {
    id: 4,
    code: 'OPD-DPMPTSP',
    name: 'Dinas Penanaman Modal & PTSP',
    address: 'Layanan Perizinan Terpadu',
    serviceType: 'Perizinan & Investasi',
    activeSurveys: 0,
    openComplaints: 0,
    status: 'INACTIVE',
  },
];
